### ISSUE TITLE
Change django-mptt requeriment to be PEP440 compatible

### ISSUE THREAD

**Issue by 8ksoft** [aldryn/aldryn-search#27]
Hi, when I try a fresh install of aldryn-search with pip I got the following:
```
  Could not find a version that satisfies the requirement django-mptt==0.5.2,==0.6,==0.6.1 (from django-cms>=2.4->aldryn-search) (from versions: 0.1, 0.2, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1)
  No distributions matching the version for django-mptt==0.5.2,==0.6,==0.6.1 (from django-cms>=2.4->aldryn-search)
```

I think your requeriments file is not compatible with the PEP440. Thanks.

**Comment by czpython** [comment]
@8ksoft django-mptt is not really a requirement of aldryn-search, it's required by django-cms, could you open this ticket in the django-cms issues. Thanks !

**Comment by 8ksoft** [comment]
Sorry, you are right!

**Comment by yakky** [comment]
djangoCMS 3.0.9 already supports pep440
