### ISSUE TITLE
ParserError isn't defined

### ISSUE THREAD

**Issue by marksweb** [aldryn/aldryn-search#37]
Just been looking over the code as I'm updating a fork of the app & in `utils.py` it looks to me as though `ParserError` is undefined so must surely cause an exception;
https://github.com/aldryn/aldryn-search/blob/master/aldryn_search/utils.py#L147

**Comment by czpython** [comment]
Thanks fixed in https://github.com/aldryn/aldryn-search/commit/ab7b0fd05f0cd9145d36e88f6fbccbac75751fb9
