### ISSUE TITLE
New Django 1.8 prereq in aldryn_search/helpers.py

### ISSUE THREAD

**Issue by trawick** [aldryn/aldryn-search#59]
This requires Django 1.8: ``from django.template import Engine``

(https://github.com/aldryn/aldryn-search/blob/master/aldryn_search/helpers.py#L3, introduced in df389ceb41b251071d527eb9954db301f552715d)

I guess the Django version checked for in the new code needs to be change?

**Comment by czpython** [comment]
Fixed by 51e0624e1099879ec15796a903c117a32e5e73da.

The idea is to keep supporting 1.6 and up.
Will update the readme also for supported cms versions.
