### ISSUE TITLE
aldryn-search affected by incompatibility beween django-haystack and aldryn-jobs

### ISSUE THREAD

**Issue by macolo** [aldryn/aldryn-search#67]
I tried to run aldryn-jobs with aldryn-search using the whoosh SearchEngine Backend but aldryn-jobs cannot get indexed correctly:

`./manage.py rebuild_index` results in `ValueError: language_code can't be null` from here: https://github.com/edoburu/django-parler/blob/master/parler/utils/conf.py#L111

Temporary work around: set `ALDRYN_JOBS_SEARCH` to `False` in settings.py

**Comment by czpython** [comment]
I think this is caused by https://github.com/django-parler/django-parler/issues/90

**Comment by leety** [comment]
hi macolo, have you found a solution to this issue?  I am running into exactly the same issue as you.

**Comment by macolo** [comment]
@leety I am a bit surprised that this is still not working as django-parler/django-parler#90 also seems to be resolved. I still have `ALDRYN_JOBS_SEARCH` set to `false`.

**Comment by leety** [comment]
@czpython, if this issue is closed, I would really like to know what is the current solution to get aldryn-search to work with the current version of parler 1.7.

**Comment by pirm-in** [comment]
hi macolo, have you found a solution to this issue? I am running into exactly the same issue as you.

**Comment by macolo** [comment]
@pirm-in I havent looked into this issue in the meantime.
