### ISSUE TITLE
aldryn-search 0.4.0 status?

### ISSUE THREAD

**Issue by jdgoettsch** [aldryn/aldryn-search#76]
[aldryn-search 0.4.0 is out on PyPi](https://pypi.python.org/pypi/aldryn-search), but the source here hasn't been updated. Has the official repo moved? Is Aldryn no longer publishing the source? On the PyPi page a non-existent repo is listed instead of this one.

**Comment by stefanfoulis** [comment]
Sorry, I forgot to push the code. I pushed it now and made a 0.4.1 release that fixes the wrong url in the pypi metadata.
