### ISSUE TITLE
Release version 0.4.2 + Recent Merge

### ISSUE THREAD

**Issue by Rugiewitz** [aldryn/aldryn-search#81]
Greetings!
I happen to notice that there was recently a PR that was merged into into the master involving excluding plugins that aren't compatible such as DjangoCMS Video and Audio.  
I was wondering if or when will you make those release public or is it already there?

**Comment by czpython** [comment]
Released https://github.com/aldryn/aldryn-search/commit/e4cd337ef05ea3796bc48c01f362e93c5dccc053
